apiVersion: v1
kind: Service
metadata:
  name: eta-sla-service
  namespace: logistics
  labels:
    app: eta-sla-service
spec:
  selector:
    app: eta-sla-service
  ports:
    - name: http
      port: 8081
      targetPort: http
