apiVersion: v1
kind: Service
metadata:
  name: analytics-exporter
  namespace: logistics
  labels:
    app: analytics-exporter
spec:
  selector:
    app: analytics-exporter
  ports:
    - name: http
      port: 8090
      targetPort: http
