// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: shipmentcore/v1/shipment_core.proto

package shipmentcorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipmentcore_v1_shipment_core_proto_rawDescGZIP(), []int{0}
}

func (x *GetShipmentRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentResponse) Reset() {
	*x = GetShipmentResponse{}
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentResponse) ProtoMessage() {}

func (x *GetShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipmentcore_v1_shipment_core_proto_rawDescGZIP(), []int{1}
}

func (x *GetShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type ListShipmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    string                 `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	SourceSystem  string                 `protobuf:"bytes,2,opt,name=source_system,json=sourceSystem,proto3" json:"source_system,omitempty"`
	RouteId       string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShipmentsRequest) Reset() {
	*x = ListShipmentsRequest{}
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShipmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShipmentsRequest) ProtoMessage() {}

func (x *ListShipmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShipmentsRequest.ProtoReflect.Descriptor instead.
func (*ListShipmentsRequest) Descriptor() ([]byte, []int) {
	return file_shipmentcore_v1_shipment_core_proto_rawDescGZIP(), []int{2}
}

func (x *ListShipmentsRequest) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *ListShipmentsRequest) GetSourceSystem() string {
	if x != nil {
		return x.SourceSystem
	}
	return ""
}

func (x *ListShipmentsRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *ListShipmentsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListShipmentsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListShipmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipments     []*Shipment            `protobuf:"bytes,1,rep,name=shipments,proto3" json:"shipments,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShipmentsResponse) Reset() {
	*x = ListShipmentsResponse{}
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShipmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShipmentsResponse) ProtoMessage() {}

func (x *ListShipmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShipmentsResponse.ProtoReflect.Descriptor instead.
func (*ListShipmentsResponse) Descriptor() ([]byte, []int) {
	return file_shipmentcore_v1_shipment_core_proto_rawDescGZIP(), []int{3}
}

func (x *ListShipmentsResponse) GetShipments() []*Shipment {
	if x != nil {
		return x.Shipments
	}
	return nil
}

func (x *ListShipmentsResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListShipmentsResponse) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Shipment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId        string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	LastEventId       string                 `protobuf:"bytes,2,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"`
	StatusCode        string                 `protobuf:"bytes,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusTs          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=status_ts,json=statusTs,proto3" json:"status_ts,omitempty"`
	SourceSystem      string                 `protobuf:"bytes,5,opt,name=source_system,json=sourceSystem,proto3" json:"source_system,omitempty"`
	LocationCode      string                 `protobuf:"bytes,6,opt,name=location_code,json=locationCode,proto3" json:"location_code,omitempty"`
	PartnerId         string                 `protobuf:"bytes,7,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	RouteId           string                 `protobuf:"bytes,8,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Payload           []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EstimatedDelivery *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_shipmentcore_v1_shipment_core_proto_rawDescGZIP(), []int{4}
}

func (x *Shipment) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *Shipment) GetLastEventId() string {
	if x != nil {
		return x.LastEventId
	}
	return ""
}

func (x *Shipment) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Shipment) GetStatusTs() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusTs
	}
	return nil
}

func (x *Shipment) GetSourceSystem() string {
	if x != nil {
		return x.SourceSystem
	}
	return ""
}

func (x *Shipment) GetLocationCode() string {
	if x != nil {
		return x.LocationCode
	}
	return ""
}

func (x *Shipment) GetPartnerId() string {
	if x != nil {
		return x.PartnerId
	}
	return ""
}

func (x *Shipment) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Shipment) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Shipment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Shipment) GetEstimatedDelivery() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDelivery
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipmentcore_v1_shipment_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_shipmentcore_v1_shipment_core_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_shipmentcore_v1_shipment_core_proto protoreflect.FileDescriptor

const file_shipmentcore_v1_shipment_core_proto_rawDesc = "" +
	"\n" +
	"#shipmentcore/v1/shipment_core.proto\x12\x0fshipmentcore.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\x12GetShipmentRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"L\n" +
	"\x13GetShipmentResponse\x125\n" +
	"\bshipment\x18\x01 \x01(\v2\x19.shipmentcore.v1.ShipmentR\bshipment\"\xa5\x01\n" +
	"\x14ListShipmentsRequest\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rsource_system\x18\x02 \x01(\tR\fsourceSystem\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\rR\x06offset\"~\n" +
	"\x15ListShipmentsResponse\x127\n" +
	"\tshipments\x18\x01 \x03(\v2\x19.shipmentcore.v1.ShipmentR\tshipments\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"\xcd\x03\n" +
	"\bShipment\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12\"\n" +
	"\rlast_event_id\x18\x02 \x01(\tR\vlastEventId\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\tR\n" +
	"statusCode\x127\n" +
	"\tstatus_ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bstatusTs\x12#\n" +
	"\rsource_system\x18\x05 \x01(\tR\fsourceSystem\x12#\n" +
	"\rlocation_code\x18\x06 \x01(\tR\flocationCode\x12\x1d\n" +
	"\n" +
	"partner_id\x18\a \x01(\tR\tpartnerId\x12\x19\n" +
	"\broute_id\x18\b \x01(\tR\arouteId\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12I\n" +
	"\x12estimated_delivery\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x11estimatedDelivery\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x8e\x02\n" +
	"\x13ShipmentCoreService\x12X\n" +
	"\vGetShipment\x12#.shipmentcore.v1.GetShipmentRequest\x1a$.shipmentcore.v1.GetShipmentResponse\x12^\n" +
	"\rListShipments\x12%.shipmentcore.v1.ListShipmentsRequest\x1a&.shipmentcore.v1.ListShipmentsResponse\x12=\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x1d.shipmentcore.v1.PingResponseB\\ZZgithub.com/dns/logistics/shipment-core-service/internal/api/shipmentcore/v1;shipmentcorev1b\x06proto3"

var (
	file_shipmentcore_v1_shipment_core_proto_rawDescOnce sync.Once
	file_shipmentcore_v1_shipment_core_proto_rawDescData []byte
)

func file_shipmentcore_v1_shipment_core_proto_rawDescGZIP() []byte {
	file_shipmentcore_v1_shipment_core_proto_rawDescOnce.Do(func() {
		file_shipmentcore_v1_shipment_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipmentcore_v1_shipment_core_proto_rawDesc), len(file_shipmentcore_v1_shipment_core_proto_rawDesc)))
	})
	return file_shipmentcore_v1_shipment_core_proto_rawDescData
}

var file_shipmentcore_v1_shipment_core_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shipmentcore_v1_shipment_core_proto_goTypes = []any{
	(*GetShipmentRequest)(nil),    // 0: shipmentcore.v1.GetShipmentRequest
	(*GetShipmentResponse)(nil),   // 1: shipmentcore.v1.GetShipmentResponse
	(*ListShipmentsRequest)(nil),  // 2: shipmentcore.v1.ListShipmentsRequest
	(*ListShipmentsResponse)(nil), // 3: shipmentcore.v1.ListShipmentsResponse
	(*Shipment)(nil),              // 4: shipmentcore.v1.Shipment
	(*PingResponse)(nil),          // 5: shipmentcore.v1.PingResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_shipmentcore_v1_shipment_core_proto_depIdxs = []int32{
	4, // 0: shipmentcore.v1.GetShipmentResponse.shipment:type_name -> shipmentcore.v1.Shipment
	4, // 1: shipmentcore.v1.ListShipmentsResponse.shipments:type_name -> shipmentcore.v1.Shipment
	6, // 2: shipmentcore.v1.Shipment.status_ts:type_name -> google.protobuf.Timestamp
	6, // 3: shipmentcore.v1.Shipment.updated_at:type_name -> google.protobuf.Timestamp
	6, // 4: shipmentcore.v1.Shipment.estimated_delivery:type_name -> google.protobuf.Timestamp
	0, // 5: shipmentcore.v1.ShipmentCoreService.GetShipment:input_type -> shipmentcore.v1.GetShipmentRequest
	2, // 6: shipmentcore.v1.ShipmentCoreService.ListShipments:input_type -> shipmentcore.v1.ListShipmentsRequest
	7, // 7: shipmentcore.v1.ShipmentCoreService.Ping:input_type -> google.protobuf.Empty
	1, // 8: shipmentcore.v1.ShipmentCoreService.GetShipment:output_type -> shipmentcore.v1.GetShipmentResponse
	3, // 9: shipmentcore.v1.ShipmentCoreService.ListShipments:output_type -> shipmentcore.v1.ListShipmentsResponse
	5, // 10: shipmentcore.v1.ShipmentCoreService.Ping:output_type -> shipmentcore.v1.PingResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shipmentcore_v1_shipment_core_proto_init() }
func file_shipmentcore_v1_shipment_core_proto_init() {
	if File_shipmentcore_v1_shipment_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipmentcore_v1_shipment_core_proto_rawDesc), len(file_shipmentcore_v1_shipment_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipmentcore_v1_shipment_core_proto_goTypes,
		DependencyIndexes: file_shipmentcore_v1_shipment_core_proto_depIdxs,
		MessageInfos:      file_shipmentcore_v1_shipment_core_proto_msgTypes,
	}.Build()
	File_shipmentcore_v1_shipment_core_proto = out.File
	file_shipmentcore_v1_shipment_core_proto_goTypes = nil
	file_shipmentcore_v1_shipment_core_proto_depIdxs = nil
}
