// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: shipmentcore/v1/shipment_core.proto

package shipmentcorev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShipmentCoreService_GetShipment_FullMethodName   = "/shipmentcore.v1.ShipmentCoreService/GetShipment"
	ShipmentCoreService_ListShipments_FullMethodName = "/shipmentcore.v1.ShipmentCoreService/ListShipments"
	ShipmentCoreService_Ping_FullMethodName          = "/shipmentcore.v1.ShipmentCoreService/Ping"
)

// ShipmentCoreServiceClient is the client API for ShipmentCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShipmentCoreServiceClient interface {
	GetShipment(ctx context.Context, in *GetShipmentRequest, opts ...grpc.CallOption) (*GetShipmentResponse, error)
	ListShipments(ctx context.Context, in *ListShipmentsRequest, opts ...grpc.CallOption) (*ListShipmentsResponse, error)
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error)
}

type shipmentCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShipmentCoreServiceClient(cc grpc.ClientConnInterface) ShipmentCoreServiceClient {
	return &shipmentCoreServiceClient{cc}
}

func (c *shipmentCoreServiceClient) GetShipment(ctx context.Context, in *GetShipmentRequest, opts ...grpc.CallOption) (*GetShipmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShipmentResponse)
	err := c.cc.Invoke(ctx, ShipmentCoreService_GetShipment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentCoreServiceClient) ListShipments(ctx context.Context, in *ListShipmentsRequest, opts ...grpc.CallOption) (*ListShipmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShipmentsResponse)
	err := c.cc.Invoke(ctx, ShipmentCoreService_ListShipments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shipmentCoreServiceClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ShipmentCoreService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShipmentCoreServiceServer is the server API for ShipmentCoreService service.
// All implementations must embed UnimplementedShipmentCoreServiceServer
// for forward compatibility.
type ShipmentCoreServiceServer interface {
	GetShipment(context.Context, *GetShipmentRequest) (*GetShipmentResponse, error)
	ListShipments(context.Context, *ListShipmentsRequest) (*ListShipmentsResponse, error)
	Ping(context.Context, *emptypb.Empty) (*PingResponse, error)
	mustEmbedUnimplementedShipmentCoreServiceServer()
}

// UnimplementedShipmentCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShipmentCoreServiceServer struct{}

func (UnimplementedShipmentCoreServiceServer) GetShipment(context.Context, *GetShipmentRequest) (*GetShipmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShipment not implemented")
}
func (UnimplementedShipmentCoreServiceServer) ListShipments(context.Context, *ListShipmentsRequest) (*ListShipmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShipments not implemented")
}
func (UnimplementedShipmentCoreServiceServer) Ping(context.Context, *emptypb.Empty) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedShipmentCoreServiceServer) mustEmbedUnimplementedShipmentCoreServiceServer() {}
func (UnimplementedShipmentCoreServiceServer) testEmbeddedByValue()                             {}

// UnsafeShipmentCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShipmentCoreServiceServer will
// result in compilation errors.
type UnsafeShipmentCoreServiceServer interface {
	mustEmbedUnimplementedShipmentCoreServiceServer()
}

func RegisterShipmentCoreServiceServer(s grpc.ServiceRegistrar, srv ShipmentCoreServiceServer) {
	// If the following call panics, it indicates UnimplementedShipmentCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShipmentCoreService_ServiceDesc, srv)
}

func _ShipmentCoreService_GetShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentCoreServiceServer).GetShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentCoreService_GetShipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentCoreServiceServer).GetShipment(ctx, req.(*GetShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentCoreService_ListShipments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShipmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentCoreServiceServer).ListShipments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentCoreService_ListShipments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentCoreServiceServer).ListShipments(ctx, req.(*ListShipmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShipmentCoreService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipmentCoreServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShipmentCoreService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipmentCoreServiceServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ShipmentCoreService_ServiceDesc is the grpc.ServiceDesc for ShipmentCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShipmentCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipmentcore.v1.ShipmentCoreService",
	HandlerType: (*ShipmentCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShipment",
			Handler:    _ShipmentCoreService_GetShipment_Handler,
		},
		{
			MethodName: "ListShipments",
			Handler:    _ShipmentCoreService_ListShipments_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _ShipmentCoreService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shipmentcore/v1/shipment_core.proto",
}
