apiVersion: v1
kind: Service
metadata:
  name: logistics-normalizer-service
  namespace: logistics
  labels:
    app: logistics-normalizer-service
spec:
  selector:
    app: logistics-normalizer-service
  ports:
    - name: http
      port: 8081
      targetPort: http
